# Generated by Django 2.2 on 2020-06-09 15:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('air_condition_system', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='detailed_list_room_db',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.CharField(max_length=50, null=True)),
                ('time', models.CharField(max_length=50, null=True)),
                ('room_no', models.IntegerField(default=0)),
                ('total_fee', models.FloatField(default=0)),
                ('target_temper', models.FloatField(default=0)),
                ('speed', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='main_controller_db',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('default_mode', models.IntegerField(default=0)),
                ('default_temper', models.IntegerField(default=0)),
                ('default_speed', models.IntegerField(default=0)),
                ('feerateL', models.FloatField(default=0)),
                ('feerateM', models.FloatField(default=0)),
                ('feerateH', models.FloatField(default=0)),
                ('state', models.IntegerField(default=-1)),
            ],
        ),
        migrations.CreateModel(
            name='room_db',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_no', models.IntegerField(default=0)),
                ('temper', models.FloatField(default=0)),
                ('customer', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='sub_controller_db',
            fields=[
                ('is_check_in', models.BooleanField(default=False)),
                ('is_power_on', models.BooleanField(default=False)),
                ('is_start_up', models.BooleanField(default=False)),
                ('mode', models.IntegerField(default=0)),
                ('speed', models.IntegerField(default=0)),
                ('target_temper', models.FloatField(default=0)),
                ('current_fee', models.FloatField(default=0)),
                ('total_fee', models.FloatField(default=0)),
                ('room_no', models.IntegerField(default=0, primary_key=True, serialize=False)),
                ('temper', models.FloatField(default=0)),
                ('feerateL', models.FloatField(default=0)),
                ('feerateM', models.FloatField(default=0)),
                ('feerateH', models.FloatField(default=0)),
                ('default_mode', models.IntegerField(default=0)),
                ('default_temper', models.IntegerField(default=0)),
                ('default_speed', models.IntegerField(default=0)),
                ('dur_time', models.FloatField(default=0)),
                ('cur_rate', models.FloatField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='server_queue_db',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_no', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='air_condition_system.sub_controller_db')),
            ],
        ),
        migrations.CreateModel(
            name='dispatch_queue_db',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_no', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='air_condition_system.sub_controller_db')),
            ],
        ),
    ]
