# Generated by Django 2.2 on 2020-06-11 04:14

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('air_condition_system', '0002_detailed_list_room_db_dispatch_queue_db_main_controller_db_room_db_server_queue_db_sub_controller_db'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=50, verbose_name='用户名')),
                ('Room', models.CharField(max_length=10, verbose_name='房间号')),
                ('Entry', models.DateTimeField(auto_now=True, verbose_name='入驻时间')),
                ('Leave', models.DateTimeField(auto_now=True, verbose_name='离开时间')),
                ('Time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='订单创建时间')),
            ],
            options={
                'verbose_name_plural': '用户',
            },
        ),
        migrations.AddField(
            model_name='main_controller_db',
            name='allow_num',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='main_controller_db',
            name='room_num',
            field=models.IntegerField(default=0),
        ),
        migrations.CreateModel(
            name='Record',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('DeDu', models.IntegerField(verbose_name='默认温度')),
                ('DangDu', models.IntegerField(verbose_name='当前温度')),
                ('Pattern', models.CharField(default='制冷', max_length=10, verbose_name='模式')),
                ('Speed', models.CharField(default=1, max_length=10, verbose_name='风速')),
                ('State', models.CharField(default='关机', max_length=10, verbose_name='当前状态')),
                ('StateDeta', models.DateTimeField(default=django.utils.timezone.now, verbose_name='开机时间')),
                ('Date', models.DateTimeField(auto_now=True, verbose_name='最后修改时间')),
                ('LeaveDeta', models.DateTimeField(default=django.utils.timezone.now, verbose_name='关机时间')),
                ('Room', models.ForeignKey(help_text='房间号', on_delete=django.db.models.deletion.CASCADE, to='air_condition_system.User')),
            ],
            options={
                'verbose_name_plural': '记录表',
            },
        ),
        migrations.CreateModel(
            name='Money',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Dmoney', models.FloatField(verbose_name='当前金额')),
                ('Lmoney', models.CharField(max_length=100, verbose_name='累计金额')),
                ('Time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间')),
                ('Room', models.ForeignKey(help_text='房间号', on_delete=django.db.models.deletion.CASCADE, to='air_condition_system.User')),
            ],
            options={
                'verbose_name_plural': '金额',
            },
        ),
    ]
