# Generated by Django 2.2 on 2020-06-12 03:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('air_condition_system', '0004_auto_20200612_1024'),
    ]

    operations = [
        migrations.RenameField(
            model_name='record',
            old_name='StateDeta',
            new_name='StartDeta',
        ),
    ]
