# Generated by Django 2.2 on 2020-06-12 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('air_condition_system', '0005_auto_20200612_1128'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dispatch_queue_db',
            name='room_no',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='server_queue_db',
            name='room_no',
            field=models.IntegerField(default=0),
        ),
    ]
