# Generated by Django 2.2 on 2020-06-12 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('air_condition_system', '0007_auto_20200613_0322'),
    ]

    operations = [
        migrations.AddField(
            model_name='record',
            name='feerate',
            field=models.FloatField(default=0),
        ),
    ]
