# Generated by Django 2.2 on 2020-06-13 01:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('air_condition_system', '0008_record_feerate'),
    ]

    operations = [
        migrations.RenameField(
            model_name='record',
            old_name='LeaveDeta',
            new_name='LeaveDate',
        ),
        migrations.RenameField(
            model_name='record',
            old_name='StartDeta',
            new_name='StartDate',
        ),
        migrations.AlterField(
            model_name='money',
            name='Room',
            field=models.IntegerField(default=0),
        ),
    ]
