# Generated by Django 2.2 on 2020-06-13 02:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('air_condition_system', '0009_auto_20200613_0956'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='money',
            name='Time',
        ),
    ]
