# Generated by Django 2.2 on 2020-06-13 02:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('air_condition_system', '0011_auto_20200613_1050'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sub_controller_db',
            name='dur_time',
            field=models.IntegerField(default=0),
        ),
    ]
