# Generated by Django 2.2 on 2020-06-05 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_controller', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='detailed_list_room_db',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
    ]
