# Generated by Django 2.2 on 2020-06-05 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_controller', '0004_auto_20200605_2308'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sub_controller_db',
            name='state',
        ),
        migrations.AddField(
            model_name='sub_controller_db',
            name='cur_rate',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='sub_controller_db',
            name='dur_time',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='sub_controller_db',
            name='is_check_in',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='sub_controller_db',
            name='is_power_on',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='sub_controller_db',
            name='is_start_up',
            field=models.BooleanField(default=False),
        ),
    ]
